### ISSUE TITLE
Problems with AppVeyor and Travis builds

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Core.Fluent#5]
Building the library with F# 3.1 fails.  F# 4.0 works. At some point in F# 4.0 we fixed code gen to no longer generate this:

```
IL_004e:  newobj     instance void [System.Runtime]System.ArgumentNullException::.ctor(class [System.Runtime]System.String)
```

And instead generate the correct thing:

```
IL_004e:  newobj     instance void [System.Runtime]System.ArgumentNullException::.ctor(string)
```

This means the Travis and AppVeyor builds fail since F# 4.0 can't be assumed. The tests fail in both cases, in both cases due to badly formed code. 

```
1) Test Error : FSharp.Core.FluentTests.ArraySmokeTests
   System.MissingMethodException : Method not found: 'Void System.ArgumentNullException..ctor(System.String)'.
   at FSharp.Core.FluentTests.ArraySmokeTests()

2) Test Error : FSharp.Core.FluentTests.ListSmokeTests
   System.MissingMethodException : Method not found: 'System.Boolean System.Collections.IEnumerator.MoveNext()'.
   at FSharp.Core.FluentTests.ListSmokeTests()

3) Test Error : FSharp.Core.FluentTests.SeqSmokeTests
   System.MissingMethodException : Method not found: 'System.Boolean System.Collections.IEnumerator.MoveNext()'.
   at FSharp.Core.FluentTests.SeqSmokeTests()

```

**Comment by dsyme** [comment]
Fixed by moving the 3.1 version of the library to Profile47, the root cause was [this bug](http://visualfsharp.codeplex.com/workitem/144) in F# 3.1, fixed in F# 4.0
